import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/lib/AuthProvider";
import { ReduxProvider } from "@/redux/Provider";
import "@/styles/main.scss";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
